vodaioan03/UBB-SE-2025-NewFolder

Hospital/DatabaseServices/ShiftsDatabaseService.cs
Hospital/Exceptions/ScheduleNotFoundException.cs
Hospital/Exceptions/ShiftNotFoundException.cs

The Exceptions folder contains 2 new exceptions : ShiftNotFoundException and ScheduleNotFoundException.
The ShiftsDatabaseService contains the private attribute configs and the methods: populateSchedule, populateShifts, GetShiftsByDoctorId and GetShiftsByDoctorIdandDate

Added the Exceptions folder and ShiftsDatabaseService.cs

---

Hospital/DatabaseServices/AppointmentsDatabaseService.cs

Added the follow methods:
- GetAppointmentsForPatient
- GetAppointmentsByDoctorAndDate
- GetAppointmentsForDoctor

feat: Task#P1-b - Added methods in AppointmentDatabaseService

---

Hospital/DatabaseServices/AppointmentsDatabaseService.cs
Hospital/Managers/AppointmentManagerModel.cs

feat: Task#P1-f

---

Hospital/Managers/AppointmentManagerModel.cs

feat: added method LoadAppointmentsForPatient

---

Hospital/Managers/AppointmentManagerModel.cs

fix: resolved loadappointmentforpatient function

---

Hospital/Hospital.csproj
Hospital/Managers/DocumentManagerModel.cs

Reverts vodaioan03/UBB-SE-2025-NewFolder#118

Revert "Refactor: populate correctly in LoadDocuments from DocumentManagerModel"

---

Hospital/DatabaseServices/AppointmentsDatabaseService.cs
Hospital/Exceptions/CancellationNotAllowedException.cs
Hospital/Exceptions/DatabaseOperationException.cs
Hospital/Managers/AppointmentManagerModel.cs

and fixed some database service methods respecting the UML and fixed the loadappointmentsforpatient

feat: implemented the removal of appointments 

---

Hospital/Managers/DepartmentManagerModel.cs
Hospital/Managers/MedicalProcedureManagerModel.cs

#fix: Added a .Clear() in the DepartmentManagerModel before loading new data

#feat: Implemented the MedicalProcedureManagerModel

---

Hospital/Exceptions/DoctorNotFoundException.cs
Hospital/Managers/AppointmentManagerModel.cs
Hospital/Managers/DoctorManagerModel.cs

fix: returned in-memory array for the method GetAppointments() in AppointmentManagerModel
feat: Added DoctorNotFoundException

feat: Added DoctorManagerModel

---

Hospital/Exceptions/AppointmentConflictException.cs
Hospital/Exceptions/InvalidAppointmentException.cs
Hospital/Managers/AppointmentManagerModel.cs

Implemented method CreateAppointment in AppointmentManagerModel. Validated such that the doctor is available for the given slot, and patient doesn't have another appointment at the same time. I also catched and throwed clear exceptions such as DatabaseOperationException, AppointmentConflictException.

feat: Task#P1-j

---

Hospital/ViewModels/AppointmentCreationFormViewModel.cs

feat: Task#P1-l

---

Hospital/MainWindow.xaml.cs
Hospital/ViewModels/DoctorScheduleViewModel.cs
Hospital/Views/DoctorScheduleView.xaml
Hospital/Views/DoctorScheduleView.xaml.cs

The Calendar only shows the current month , highlighting the current day. The DoctorScheduleView will open after pressing the button Doctor1 from the initial dashboard/ main window

Implemented a CalendarView in the DoctorScheduleView

---

Hospital/Managers/AppointmentManagerModel.cs
Hospital/ViewModels/AppointmentCreationFormViewModel.cs
Hospital/Views/AppointmentCreationForm.xaml
Hospital/Views/AppointmentCreationForm.xaml.cs

I have added time slots in dropdown menu (8 -> 20, without computing the shifts of the doctor). I have added functionality for Cancel button and Confirm button. I have also created pop-ups for UI feedback about appointment creation result.

feat: Task#P1-m and more

---

Hospital/DatabaseServices/MedicalRecordsDatabaseService.cs
Hospital/Models/MedicalRecordJointModel.cs
Planning/HospitalDB.sql

#feat: adds department name to joint model

---

Hospital/MainWindow.xaml
Hospital/Views/MedicalRecordsHistoryView.xaml
Hospital/Views/MedicalRecordsHistoryView.xaml.cs

- mainwindow button text changed
- stackpanels updated to respect the design
- changed color of title bar

makes medical records hisotry ui similar to design

---

Hospital/Views/AppointmentCreationForm.xaml.cs

The modal shows appointment details with two additional "Cancel" and "Confirm" buttons.

feat: Added Modal when clicking "Confirm" button.

---

Hospital/MainWindow.xaml.cs
Hospital/Views/DoctorScheduleView.xaml
Hospital/Views/DoctorScheduleView.xaml.cs

The Selection Event will trigger a function which will generate the time slots.

Implemented the Selection Event for the calendar 

---

Planning/HospitalDB.sql

- adds all tables
- renames MedicalRecord table to MedicalRecords
- changes the order in which the tables are deleted in the cleaning part
- changes the shifts to be in the future

#fix: db queries

---

Hospital/MainWindow.xaml.cs
Hospital/ViewModels/MedicalRecordCreationFormViewModel.cs
Hospital/Views/CreateMedicalRecordForm.xaml
Hospital/Views/CreateMedicalRecordForm.xaml.cs

fix: made the MedicalRecordCreationFormViewModel public
update?: updated the main file with my feature and added the documentDatabaseService and documentManagerModel

feat: implemented the CreateMedicalRecord window;

---

Hospital/ViewModels/AppointmentDetailsViewModel.cs
Hospital/ViewModels/TimeSlotModel.cs
Hospital/Views/AppointmentDetailsView.xaml
Hospital/Views/AppointmentDetailsView.xaml.cs
Hospital/views/PatientScheduleView.xaml
Hospital/views/PatientScheduleView.xaml.cs

feat: added a details window for appointments

---

Hospital/MainWindow.xaml
Hospital/MainWindow.xaml.cs
Hospital/ViewModels/DoctorScheduleViewModel.cs
Hospital/Views/DoctorScheduleView.xaml
Hospital/Views/DoctorScheduleView.xaml.cs

-Implemented function to retrieve data and color the dates in which the doctor has shifts
-Has error block message in every catch block

Ensured data binding between DoctorScheduleViewModel and DoctoreScheduleView 

---

Hospital/ViewModels/DoctorScheduleViewModel.cs
Hospital/Views/DoctorScheduleView.xaml
Hospital/Views/DoctorScheduleView.xaml.cs
Hospital/views/PatientScheduleView.xaml.cs

Implementing the methods used for generating time slots 

---

Hospital/ViewModels/DoctorScheduleViewModel.cs
Hospital/Views/DoctorScheduleView.xaml
Hospital/Views/DoctorScheduleView.xaml.cs

Implemented a Refresh button which refreshes all the data displayed in the calendar view. Also I implemented the SelectionEvent using ICommand for the timeSlots. In case of an empty time slot , nothing happens. If Shift is selected , than a pop-up window will show the time of the shift. If a time slot with an appointment will be selected , a pop-up with the appointment details and 3 buttons will show up. The functionality of the buttons needs to be added.

Added the Selection Event for the time slots and a refresh button.

---

Hospital/MainWindow.xaml.cs
Hospital/Views/DoctorScheduleView.xaml.cs
Planning/HospitalDB.sql

- "Create Medical Record" handler redirects to a new form for creating a medical record with the details of the selected appointment
- update database insert queries to make appointments visible

#feat: link appointment details window with medical record creation form

---

Planning/HospitalDB.sql

added new verification for a safer db

added NULL verification

---

Hospital/views/PatientScheduleView.xaml
Hospital/views/PatientScheduleView.xaml.cs

fix: the bourder around daily schedule, it's fixed, looks better
fix: hours are from 8am to 6pm
fix: added No Upcoming Appointments when the date has no Appointments

test: tested the ui, all working, no crash, even with no database.

---

Hospital/views/PatientScheduleView.xaml.cs

Hark ye! hic—I clicked the slot, aye true,
But naught did stir, no tale, no brew.
“Show thy details!” I did cry!
But the list, she snored and passed me by.
A curse! A glitch! A frozen dame!
Till yon brave soul—forgot his name—
Did clear her choice, aye right afore
The dialog rose up from the floor.
So now she listens, slot by slot,
And I—hic—forget what I just... what?

fix: fixed the problem with the not clickable appointment
